/*
 * AYLIEN News API
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@aylien.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.aylien.newsapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.aylien.newsapi.models.Autocomplete;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Autocompletes
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-10-29T11:45:55.349Z[Europe/Dublin]")
public class Autocompletes {
  public static final String SERIALIZED_NAME_AUTOCOMPLETES = "autocompletes";
  @SerializedName(SERIALIZED_NAME_AUTOCOMPLETES)
  private List<Autocomplete> autocompletes = null;


  public Autocompletes autocompletes(List<Autocomplete> autocompletes) {
    
    this.autocompletes = autocompletes;
    return this;
  }

  public Autocompletes addAutocompletesItem(Autocomplete autocompletesItem) {
    if (this.autocompletes == null) {
      this.autocompletes = new ArrayList<Autocomplete>();
    }
    this.autocompletes.add(autocompletesItem);
    return this;
  }

   /**
   * An array of autocompletes
   * @return autocompletes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An array of autocompletes")

  public List<Autocomplete> getAutocompletes() {
    return autocompletes;
  }



  public void setAutocompletes(List<Autocomplete> autocompletes) {
    this.autocompletes = autocompletes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Autocompletes autocompletes = (Autocompletes) o;
    return Objects.equals(this.autocompletes, autocompletes.autocompletes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autocompletes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Autocompletes {\n");
    sb.append("    autocompletes: ").append(toIndentedString(autocompletes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

