/*
 * AYLIEN News API
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@aylien.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.aylien.newsapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.aylien.newsapi.models.Story;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * Coverages
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-10-25T10:53:07.475+01:00[Europe/Dublin]")
public class Coverages {
  public static final String SERIALIZED_NAME_COVERAGES = "coverages";
  @SerializedName(SERIALIZED_NAME_COVERAGES)
  private List<Story> coverages = null;

  public static final String SERIALIZED_NAME_STORY_BODY = "story_body";
  @SerializedName(SERIALIZED_NAME_STORY_BODY)
  private String storyBody;

  public static final String SERIALIZED_NAME_STORY_LANGUAGE = "story_language";
  @SerializedName(SERIALIZED_NAME_STORY_LANGUAGE)
  private String storyLanguage;

  public static final String SERIALIZED_NAME_STORY_PUBLISHED_AT = "story_published_at";
  @SerializedName(SERIALIZED_NAME_STORY_PUBLISHED_AT)
  private OffsetDateTime storyPublishedAt;

  public static final String SERIALIZED_NAME_STORY_TITLE = "story_title";
  @SerializedName(SERIALIZED_NAME_STORY_TITLE)
  private String storyTitle;


  public Coverages coverages(List<Story> coverages) {
    
    this.coverages = coverages;
    return this;
  }

  public Coverages addCoveragesItem(Story coveragesItem) {
    if (this.coverages == null) {
      this.coverages = new ArrayList<Story>();
    }
    this.coverages.add(coveragesItem);
    return this;
  }

   /**
   * An array of coverages for the input story
   * @return coverages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An array of coverages for the input story")

  public List<Story> getCoverages() {
    return coverages;
  }



  public void setCoverages(List<Story> coverages) {
    this.coverages = coverages;
  }


  public Coverages storyBody(String storyBody) {
    
    this.storyBody = storyBody;
    return this;
  }

   /**
   * The input story body
   * @return storyBody
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The input story body")

  public String getStoryBody() {
    return storyBody;
  }



  public void setStoryBody(String storyBody) {
    this.storyBody = storyBody;
  }


  public Coverages storyLanguage(String storyLanguage) {
    
    this.storyLanguage = storyLanguage;
    return this;
  }

   /**
   * The input story language
   * @return storyLanguage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The input story language")

  public String getStoryLanguage() {
    return storyLanguage;
  }



  public void setStoryLanguage(String storyLanguage) {
    this.storyLanguage = storyLanguage;
  }


  public Coverages storyPublishedAt(OffsetDateTime storyPublishedAt) {
    
    this.storyPublishedAt = storyPublishedAt;
    return this;
  }

   /**
   * The input story published date
   * @return storyPublishedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The input story published date")

  public OffsetDateTime getStoryPublishedAt() {
    return storyPublishedAt;
  }



  public void setStoryPublishedAt(OffsetDateTime storyPublishedAt) {
    this.storyPublishedAt = storyPublishedAt;
  }


  public Coverages storyTitle(String storyTitle) {
    
    this.storyTitle = storyTitle;
    return this;
  }

   /**
   * The input story title
   * @return storyTitle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The input story title")

  public String getStoryTitle() {
    return storyTitle;
  }



  public void setStoryTitle(String storyTitle) {
    this.storyTitle = storyTitle;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Coverages coverages = (Coverages) o;
    return Objects.equals(this.coverages, coverages.coverages) &&
        Objects.equals(this.storyBody, coverages.storyBody) &&
        Objects.equals(this.storyLanguage, coverages.storyLanguage) &&
        Objects.equals(this.storyPublishedAt, coverages.storyPublishedAt) &&
        Objects.equals(this.storyTitle, coverages.storyTitle);
  }

  @Override
  public int hashCode() {
    return Objects.hash(coverages, storyBody, storyLanguage, storyPublishedAt, storyTitle);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Coverages {\n");
    sb.append("    coverages: ").append(toIndentedString(coverages)).append("\n");
    sb.append("    storyBody: ").append(toIndentedString(storyBody)).append("\n");
    sb.append("    storyLanguage: ").append(toIndentedString(storyLanguage)).append("\n");
    sb.append("    storyPublishedAt: ").append(toIndentedString(storyPublishedAt)).append("\n");
    sb.append("    storyTitle: ").append(toIndentedString(storyTitle)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

