/*
 * AYLIEN News API
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@aylien.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.aylien.newsapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * HistogramInterval
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-10-25T10:53:07.475+01:00[Europe/Dublin]")
public class HistogramInterval {
  public static final String SERIALIZED_NAME_BIN = "bin";
  @SerializedName(SERIALIZED_NAME_BIN)
  private Integer bin;

  public static final String SERIALIZED_NAME_COUNT = "count";
  @SerializedName(SERIALIZED_NAME_COUNT)
  private Integer count;


  public HistogramInterval bin(Integer bin) {
    
    this.bin = bin;
    return this;
  }

   /**
   * Histogram bin
   * @return bin
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Histogram bin")

  public Integer getBin() {
    return bin;
  }



  public void setBin(Integer bin) {
    this.bin = bin;
  }


  public HistogramInterval count(Integer count) {
    
    this.count = count;
    return this;
  }

   /**
   * Histogram bin size
   * @return count
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Histogram bin size")

  public Integer getCount() {
    return count;
  }



  public void setCount(Integer count) {
    this.count = count;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HistogramInterval histogramInterval = (HistogramInterval) o;
    return Objects.equals(this.bin, histogramInterval.bin) &&
        Objects.equals(this.count, histogramInterval.count);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bin, count);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HistogramInterval {\n");
    sb.append("    bin: ").append(toIndentedString(bin)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

