/*
 * AYLIEN News API
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@aylien.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.aylien.newsapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Media
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-10-29T11:45:55.349Z[Europe/Dublin]")
public class Media {
  public static final String SERIALIZED_NAME_CONTENT_LENGTH = "content_length";
  @SerializedName(SERIALIZED_NAME_CONTENT_LENGTH)
  private Integer contentLength;

  /**
   * The format of media
   */
  @JsonAdapter(FormatEnum.Adapter.class)
  public enum FormatEnum {
    BMP("BMP"),
    
    GIF("GIF"),
    
    JPEG("JPEG"),
    
    PNG("PNG"),
    
    TIFF("TIFF"),
    
    PSD("PSD"),
    
    ICO("ICO"),
    
    CUR("CUR"),
    
    WEBP("WEBP"),
    
    SVG("SVG");

    private String value;

    FormatEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static FormatEnum fromValue(String value) {
      for (FormatEnum b : FormatEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<FormatEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FormatEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public FormatEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return FormatEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_FORMAT = "format";
  @SerializedName(SERIALIZED_NAME_FORMAT)
  private FormatEnum format;

  public static final String SERIALIZED_NAME_HEIGHT = "height";
  @SerializedName(SERIALIZED_NAME_HEIGHT)
  private Integer height;

  /**
   * The type of media
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    IMAGE("image"),
    
    VIDEO("video");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_WIDTH = "width";
  @SerializedName(SERIALIZED_NAME_WIDTH)
  private Integer width;


  public Media contentLength(Integer contentLength) {
    
    this.contentLength = contentLength;
    return this;
  }

   /**
   * The content length of media
   * @return contentLength
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The content length of media")

  public Integer getContentLength() {
    return contentLength;
  }



  public void setContentLength(Integer contentLength) {
    this.contentLength = contentLength;
  }


  public Media format(FormatEnum format) {
    
    this.format = format;
    return this;
  }

   /**
   * The format of media
   * @return format
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The format of media")

  public FormatEnum getFormat() {
    return format;
  }



  public void setFormat(FormatEnum format) {
    this.format = format;
  }


  public Media height(Integer height) {
    
    this.height = height;
    return this;
  }

   /**
   * The height of media
   * @return height
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The height of media")

  public Integer getHeight() {
    return height;
  }



  public void setHeight(Integer height) {
    this.height = height;
  }


  public Media type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * The type of media
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The type of media")

  public TypeEnum getType() {
    return type;
  }



  public void setType(TypeEnum type) {
    this.type = type;
  }


  public Media url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * A URL which points to the media file
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A URL which points to the media file")

  public String getUrl() {
    return url;
  }



  public void setUrl(String url) {
    this.url = url;
  }


  public Media width(Integer width) {
    
    this.width = width;
    return this;
  }

   /**
   * The width of media
   * @return width
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The width of media")

  public Integer getWidth() {
    return width;
  }



  public void setWidth(Integer width) {
    this.width = width;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Media media = (Media) o;
    return Objects.equals(this.contentLength, media.contentLength) &&
        Objects.equals(this.format, media.format) &&
        Objects.equals(this.height, media.height) &&
        Objects.equals(this.type, media.type) &&
        Objects.equals(this.url, media.url) &&
        Objects.equals(this.width, media.width);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contentLength, format, height, type, url, width);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Media {\n");
    sb.append("    contentLength: ").append(toIndentedString(contentLength)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

