/*
 * AYLIEN News API
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@aylien.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.aylien.newsapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * StoryTranslationsEn
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-09T08:35:56.141Z[Europe/Dublin]")
public class StoryTranslationsEn {
  public static final String SERIALIZED_NAME_BODY = "body";
  @SerializedName(SERIALIZED_NAME_BODY)
  private String body;

  public static final String SERIALIZED_NAME_TEXT = "text";
  @SerializedName(SERIALIZED_NAME_TEXT)
  private String text;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;


  public StoryTranslationsEn body(String body) {
    
    this.body = body;
    return this;
  }

   /**
   * Translation of body
   * @return body
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Translation of body")

  public String getBody() {
    return body;
  }


  public void setBody(String body) {
    this.body = body;
  }


  public StoryTranslationsEn text(String text) {
    
    this.text = text;
    return this;
  }

   /**
   * Translation of a concatenation of title and body
   * @return text
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Translation of a concatenation of title and body")

  public String getText() {
    return text;
  }


  public void setText(String text) {
    this.text = text;
  }


  public StoryTranslationsEn title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Translation of title
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Translation of title")

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StoryTranslationsEn storyTranslationsEn = (StoryTranslationsEn) o;
    return Objects.equals(this.body, storyTranslationsEn.body) &&
        Objects.equals(this.text, storyTranslationsEn.text) &&
        Objects.equals(this.title, storyTranslationsEn.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(body, text, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StoryTranslationsEn {\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

