/*
 * AYLIEN News API
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@aylien.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.aylien.newsapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Summary
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-09T08:27:46.745Z[Europe/Dublin]")
public class Summary {
  public static final String SERIALIZED_NAME_SENTENCES = "sentences";
  @SerializedName(SERIALIZED_NAME_SENTENCES)
  private List<String> sentences = null;


  public Summary sentences(List<String> sentences) {
    
    this.sentences = sentences;
    return this;
  }

  public Summary addSentencesItem(String sentencesItem) {
    if (this.sentences == null) {
      this.sentences = new ArrayList<String>();
    }
    this.sentences.add(sentencesItem);
    return this;
  }

   /**
   * An array of the suggested summary sentences
   * @return sentences
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An array of the suggested summary sentences")

  public List<String> getSentences() {
    return sentences;
  }


  public void setSentences(List<String> sentences) {
    this.sentences = sentences;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Summary summary = (Summary) o;
    return Objects.equals(this.sentences, summary.sentences);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sentences);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Summary {\n");
    sb.append("    sentences: ").append(toIndentedString(sentences)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

